# Generated by Django 4.2.3 on 2023-08-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0016_remove_checkout_item_remove_checkout_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_user',
            name='joindate',
            field=models.DateField(null=True),
        ),
    ]
